language: rust
cache: cargo
rust:
    - stable
    - 1.19.0
    - 1.18.0
    - 1.17.0
    - 1.16.0
    - beta
    - nightly
os:
    - osx
    - linux
    
matrix:
    allow_failures:
        - rust: nightly
